### ISSUE TITLE
re-run the generator

### ISSUE THREAD

**Issue by geoffreydhuyvetters** [thibmaek/bpost#1]
There was a breaking bug in one of the previous version
I think it's a good idea to update your generator and re-run it.

**Comment by thibmaek** [comment]
Thanks for the notice will update it later today. Luckily not publishes on npm registry yet 😅

**Comment by thibmaek** [comment]
@duivvv Updated generator, generated a new generator and diffed it against the current generator where I then replaced the lines that had to be replaced.

Can you doublecheck if I fixed it in https://github.com/thibmaek/bpost/commit/478a9731102332d5d42ace0c417f6e97729ca6e2 and https://github.com/thibmaek/bpost/commit/39438413d62c2b68e55f057887746d00ea08fa58 ?

**Comment by geoffreydhuyvetters** [comment]
think so, but I'm working on (another) more silent scripts attempt..
too much data flowing in the CLI now

**Comment by thibmaek** [comment]
I'll keep an eye open on the generator ;)
Will close this for now.

**Comment by geoffreydhuyvetters** [comment]
https://github.com/duivvv/generator-module-boilerplate/releases/tag/v1.4.0

**Comment by thibmaek** [comment]
@duivvv thanks ;) was actually just looking at the most recent commits and will add this to 0.1.1 milestone
