### ISSUE TITLE
Reduce the size for lodash dependency

### ISSUE THREAD

**Issue by thibmaek** [thibmaek/bpost#18]
Below screenshot shows that lodash currently installs the full 4.8MB module and only filter and find are used. Need to find a better way to include lodash as a dependency.

![screenshot 2016-11-20 00 42 30](https://cloud.githubusercontent.com/assets/6213695/20459234/64ada614-aeba-11e6-9a50-35917476c773.png)

**Comment by geoffreydhuyvetters** [comment]
https://github.com/lodash/babel-plugin-lodash

**Comment by geoffreydhuyvetters** [comment]
all lodash methods are exported as separate modules btw https://www.npmjs.com/package/lodash.find

**Comment by thibmaek** [comment]
Yup, went for the last on in https://github.com/thibmaek/bpost/commit/32d471576c0f6f00ebfdf0c7f7fd8f9866d78834

Will be in the 0.2.0 release but still working on some other stuff right now ;)
