### ISSUE TITLE
Update the release.json

### ISSUE THREAD

**Issue by thibmaek** [thibmaek/bpost#19]
Append:
`"changelogCommand": "git log --pretty=format:'* %s (%h)' v[REV_RANGE]"`

**Comment by geoffreydhuyvetters** [comment]
not working with my setup, thinking on migrating https://github.com/duivvv/generator-module-boilerplate to https://github.com/sindresorhus/np

**Comment by thibmaek** [comment]
Already checked it out, seems like it's indeed a more suitable (& nice looking) solution
