### ISSUE TITLE
Use GlobalFetch instead of axios

### ISSUE THREAD

**Issue by thibmaek** [thibmaek/bpost#4]
axios was used since there was an issue with GlobalFetch due to CORS requests not being supported API-side.

Preferably `src/lib/composedFetch.js` would use the following syntax (with a check for 200 status of course):
```js
export default id =>
  fetch(`http://track.bpost.be/btr/api/items?itemIdentifier=${id}`)
    .then(res => res.data[0])
    .catch(e => console.error(e));
```

This would be ideal but failed because fetch did not complete due to the bpost api endpoint not setting `Header: 'access-allow-control-origin'`and thus not supporting CORS requests. Fetch offers a `mode: 'no-cors'` to return an opaque response but contains no data.

__Note__: also include a fetch polyfill for non supported environments like node. isormophic-fetch would work best.

**Comment by geoffreydhuyvetters** [comment]
I'm trying to fix this in https://github.com/duivvv/api-helper
maybe you could use it as a dependency? (still WIP, but nearly finished)

**Comment by thibmaek** [comment]
Yup, I was gonna go for this. Already tried with the dist/api-helper.min.js and worked great but was waiting till you were finished with it and it's published on npm. Give me a shout when it's on npm and I'll implement this ;)
