### ISSUE TITLE
Refactor API to instantiate first and use methods on that instance

### ISSUE THREAD

**Issue by thibmaek** [thibmaek/bpost#7]
In 0.1.0 and 0.1.1 all methods need to be called with an id passed to it each time:

```js
import bpost from 'bpost';

const id = `323267009691651472`;

const a = bpost.getStatus(id);
const b = bpost.openingHours(id, 'monday');
const c = bpost. getPackageWeight(id);
…
```

Ideally the module would be created as an instance and then the id would be known to all methods:

```js
import bpost from 'bpost';

bpost.setup(`323267009691651472`); // something like: setup, create, instantiate …

const a = bpost.getStatus();
const b = bpost.openingHours(`monday`);
```

**Comment by geoffreydhuyvetters** [comment]
maybe this approach would work? https://github.com/duivvv/api-helper/blob/development/example/script.js

**Comment by thibmaek** [comment]
Will look into it this afternoon, thanks!
